# valkiriacloud.com (dominio raiz) -> landing page
server {
    listen 80;
    server_name valkiriacloud.com www.valkiriacloud.com;
    root /var/www/valkiria;
    index index.html;
    location / { try_files $uri $uri/ =404; }
}
